- name: Install JDK8
  package: name=openjdk-8-jdk-headless state=present

- name: AddUser "wildfly"
  user:
    name: wildfly
    system: yes

- name: download and unzip wildfly
  unarchive:
    src: 'http://download.jboss.org/wildfly/11.0.0.Final/wildfly-11.0.0.Final.tar.gz'
    dest: '/opt/'
    owner: wildfly
    remote_src: yes

- name: Rename wildfly-11.0.0.Final into wildfly
  command: mv '/opt/wildfly-11.0.0.Final/' '/opt/wildfly/'

- name: Mkdir "/etc/wildfly"
  file:
    path: '/etc/wildfly/'
    state: directory
    owner: wildfly
    group: wildfly
    mode: 0755

- name: Cp /opt/wildfly/docs/contrib/scripts/systemd/wildfly.conf into /etc/wildfly/
  copy:
    src: '/opt/wildfly/docs/contrib/scripts/systemd/wildfly.conf'
    dest: '/etc/wildfly/'
    owner: wildfly
    group: wildfly
    mode: 0755
    remote_src: yes

- name: Cp /opt/wildfly/docs/contrib/scripts/systemd/wildfly.service into /etc/systemd/system
  copy:
    src: '/opt/wildfly/docs/contrib/scripts/systemd/wildfly.service'
    dest: '/etc/systemd/system/'
    remote_src: yes

- name: Mkdir /opt/wildfly/bin
  file:
    path: '/opt/wildfly/bin'
    state: directory
    owner: wildfly
    group: wildfly
    mode: 0755


- name: Cp /opt/wildfly/docs/contrib/scripts/systemd/lauch.sh into /opt/wildfly/bin
  copy:
    src: '/opt/wildfly/docs/contrib/scripts/systemd/launch.sh'
    dest: '/opt/wildfly/bin'
    owner: wildfly
    group: wildfly
    mode: 0755
    remote_src: yes
  notify: 
     - run wildfly


- name: run wildfly 
  systemd:
    state: started
    daemon_reload: yes
    name: wildfly

